sw-acesso-001:
  hostname: 192.168.1.1
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-002:
  hostname: 192.168.1.2
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-003:
  hostname: 192.168.1.3
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-004:
  hostname: 192.168.1.4
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-005:
  hostname: 192.168.1.5
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-006:
  hostname: 192.168.1.6
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-007:
  hostname: 192.168.1.7
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-008:
  hostname: 192.168.1.8
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-009:
  hostname: 192.168.1.9
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-010:
  hostname: 192.168.1.10
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-011:
  hostname: 192.168.1.11
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-012:
  hostname: 192.168.1.12
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-013:
  hostname: 192.168.1.13
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-014:
  hostname: 192.168.1.14
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-015:
  hostname: 192.168.1.15
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-016:
  hostname: 192.168.1.16
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-017:
  hostname: 192.168.1.17
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-018:
  hostname: 192.168.1.18
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-019:
  hostname: 192.168.1.19
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-020:
  hostname: 192.168.1.20
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-021:
  hostname: 192.168.1.21
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-022:
  hostname: 192.168.1.22
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-023:
  hostname: 192.168.1.23
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-024:
  hostname: 192.168.1.24
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-025:
  hostname: 192.168.1.25
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-026:
  hostname: 192.168.1.26
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-027:
  hostname: 192.168.1.27
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-028:
  hostname: 192.168.1.28
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-029:
  hostname: 192.168.1.29
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-030:
  hostname: 192.168.1.30
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-031:
  hostname: 192.168.1.31
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-032:
  hostname: 192.168.1.32
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-033:
  hostname: 192.168.1.33
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-034:
  hostname: 192.168.1.34
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-035:
  hostname: 192.168.1.35
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-036:
  hostname: 192.168.1.36
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-037:
  hostname: 192.168.1.37
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-038:
  hostname: 192.168.1.38
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-039:
  hostname: 192.168.1.39
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-040:
  hostname: 192.168.1.40
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-041:
  hostname: 192.168.1.41
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-042:
  hostname: 192.168.1.42
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-043:
  hostname: 192.168.1.43
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-044:
  hostname: 192.168.1.44
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-045:
  hostname: 192.168.1.45
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-046:
  hostname: 192.168.1.46
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-047:
  hostname: 192.168.1.47
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-048:
  hostname: 192.168.1.48
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-049:
  hostname: 192.168.1.49
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-050:
  hostname: 192.168.1.50
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 10
    setor: Financeiro
sw-acesso-051:
  hostname: 192.168.1.51
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-052:
  hostname: 192.168.1.52
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-053:
  hostname: 192.168.1.53
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-054:
  hostname: 192.168.1.54
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-055:
  hostname: 192.168.1.55
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-056:
  hostname: 192.168.1.56
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-057:
  hostname: 192.168.1.57
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-058:
  hostname: 192.168.1.58
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-059:
  hostname: 192.168.1.59
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-060:
  hostname: 192.168.1.60
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-061:
  hostname: 192.168.1.61
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-062:
  hostname: 192.168.1.62
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-063:
  hostname: 192.168.1.63
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-064:
  hostname: 192.168.1.64
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-065:
  hostname: 192.168.1.65
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-066:
  hostname: 192.168.1.66
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-067:
  hostname: 192.168.1.67
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-068:
  hostname: 192.168.1.68
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-069:
  hostname: 192.168.1.69
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-070:
  hostname: 192.168.1.70
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-071:
  hostname: 192.168.1.71
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-072:
  hostname: 192.168.1.72
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-073:
  hostname: 192.168.1.73
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-074:
  hostname: 192.168.1.74
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-075:
  hostname: 192.168.1.75
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-076:
  hostname: 192.168.1.76
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-077:
  hostname: 192.168.1.77
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-078:
  hostname: 192.168.1.78
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-079:
  hostname: 192.168.1.79
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-080:
  hostname: 192.168.1.80
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-081:
  hostname: 192.168.1.81
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-082:
  hostname: 192.168.1.82
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-083:
  hostname: 192.168.1.83
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-084:
  hostname: 192.168.1.84
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-085:
  hostname: 192.168.1.85
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-086:
  hostname: 192.168.1.86
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-087:
  hostname: 192.168.1.87
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-088:
  hostname: 192.168.1.88
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-089:
  hostname: 192.168.1.89
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-090:
  hostname: 192.168.1.90
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-091:
  hostname: 192.168.1.91
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-092:
  hostname: 192.168.1.92
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-093:
  hostname: 192.168.1.93
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-094:
  hostname: 192.168.1.94
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-095:
  hostname: 192.168.1.95
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-096:
  hostname: 192.168.1.96
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-097:
  hostname: 192.168.1.97
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-098:
  hostname: 192.168.1.98
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-099:
  hostname: 192.168.1.99
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
sw-acesso-100:
  hostname: 192.168.1.100
  groups:
  - switches_acesso
  data:
    interface: GigabitEthernet0/1
    vlan: 20
    setor: Operacional
